document.writeln("<!--王紫-->");
new_element=document.createElement("link");
new_element.setAttribute("rel","stylesheet");
new_element.setAttribute("type","text/css");
new_element.setAttribute("href","/meowcat/Resources/css/navi_css.css");
document.body.appendChild(new_element);
document.writeln("<?php include(\'User_get.php\'); ?>");
document.writeln("    	<div class=\'container-fiuled\' id=\'row1\'>");
document.writeln("			<div class=\'row clearfix\'>");
document.writeln("				<div class=\'col-md-12 column\'>");
document.writeln("					<nav class=\'navbar navbar-expand-sm\' role=\'navigation\'>");
document.writeln("						<div class=\'navbar-header\'>");
document.writeln("							<a class=\'navbar-brand\' href=\'#\'>");
document.writeln("								<img alt=\'logo\' width=\'180px\' src=\'/meowcat/image/logo1.png\'/>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("							<ul class=\'nav navbar-nav pull-right\'>");
document.writeln("								<li class=\'dropdown\'>");
document.writeln("									<a class=\'dropdown-toggle\' data-toggle=\'dropdown\'>开始工作<strong class=\'caret\'></strong></a>");
document.writeln("									<ul class=\'dropdown-menu\'>");
document.writeln("										<li>");
document.writeln("											<a href=\'/meowcat/web/translator/to_translate/task.html\'>个人项目</a>");
document.writeln("										</li>");
document.writeln("										<li class=\'divider\'>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("									 		<a href=\'/meowcat/web/translator/to_translate/task_tm.html\'>团队项目</a>");
document.writeln("										</li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'/meowcat/web/translator/translfile.html\'>个人档案</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'/meowcat/modules/Users/Users_logout.php\'>注销</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("					</nav>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");

document.writeln("		<div class=\'container-fiuled\' >");
document.writeln("			<div class=\'row clearfix\'>");
document.writeln("				<div class=\'col-md-2 column\' id=\'row2col1\'>");
document.writeln("					<ul class=\'nav nav-stacked text-center\'>");
document.writeln("						<li>");
document.writeln("							<table id=\'table0\'>");
document.writeln("								<tr>");
document.writeln("									<td colspan=\'2\'>");
document.writeln("										<svg width=\'6em\' height=\'6em\' viewBox=\'0 0 16 16\' class=\'bi bi-person-circle\' fill=\'currentColor\' xmlns=\'http://www.w3.org/2000/svg\'>");
document.writeln("  											<path d=\'M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z\'/>");
document.writeln("  											<path fill-rule=\'evenodd\' d=\'M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z\'/>");
document.writeln(" 											<path fill-rule=\'evenodd\' d=\'M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z\'/>");
document.writeln("										</svg>");
document.writeln("									<td>");
document.writeln("								</tr>");

document.writeln("							</table>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'/meowcat/web/translator/to_translate/tasktermlist.html\'>术语库</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'/meowcat/web/translator/to_translate/taskmemorlist.html\'>翻译记忆库</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'/meowcat/web/common/taskmacht.html\'>机器翻译</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'/meowcat/web/common/taskstyle.html\'>风格指南</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'/meowcat/web/main/aboutus.html\'>关于我们</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("<div class=\'container-fluid col-md-10 column\' style=\'margin-top:80px\'>");
